In [24]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import scipy as sp
from scipy import stats
import scipy.stats.mstats as mst
import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.stats.anova import anova_lm
from statsmodels.stats.multicomp import (pairwise_tukeyhsd, MultiComparison)

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

data = pd.read_csv('olstest.csv', low_memory=False)

In [2]:
data.head()

   ID  Score  Income Treatment
0   1     12    17.5   Method1
1   2     39   104.6   Method1
2   3     36    64.7   Method1
3   4     17    47.0   Method1
4   5     25    22.0   Method1

In [26]:
formula = 'Score ~ Income + C(Treatment)'
lm = smf.ols(formula, data).fit()

In [10]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Score   R-squared:                       0.639
Model:                            OLS   Adj. R-squared:                  0.593
Method:                 Least Squares   F-statistic:                     13.73
Date:                Sun, 06 Dec 2015   Prob (F-statistic):           1.50e-06
Time:                        00:49:30   Log-Likelihood:                -121.18
No. Observations:                  36   AIC:                             252.4
Df Residuals:                      31   BIC:                             260.3
Df Model:                           4
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [95.0% Conf. Int.]
-----------------------------------------------------------------------------------------
C(Treatment)[Method1]     8.0424      3.822      2.104      0.044         0.247    15.838
C(Treatment)[Method2]    14.3132      4.469      3.203      0.003         5.199    23.428
C(Treatment)[Method3]     5.5926      3.840      1.456      0.155        -2.239    13.424
C(Treatment)[Method4]     2.8567      3.376      0.846      0.404        -4.029     9.743
Income                    0.3225      0.059      5.424      0.000         0.201     0.444
==============================================================================
Omnibus:                        1.028   Durbin-Watson:                   2.235
Prob(Omnibus):                  0.598   Jarque-Bera (JB):                0.453
Skew:                           0.262   Prob(JB):                        0.797
Kurtosis:                       3.162   Cond. No.                         275.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [17]:
anova = anova_lm(lm)

In [18]:
anova

              df        sum_sq      mean_sq          F        PR(>F)
C(Treatment)   4  20591.125000  5147.781250  90.234213  1.274121e-16
Income         1   1678.352687  1678.352687  29.419438  6.367062e-06
Residual      31   1768.522313    57.049107        NaN           NaN

In [20]:
X = lm.model.data.orig_exog

In [21]:
import patsy

In [27]:
y, X = patsy.dmatrices(formula, data, return_type='dataframe')

In [29]:
X

,Intercept,C(Treatment)[T.Method2],C(Treatment)[T.Method3],C(Treatment)[T.Method4],Income
0,1,0,0,0,17.5
1,1,0,0,0,104.6
2,1,0,0,0,64.7
3,1,0,0,0,47.0
4,1,0,0,0,22.0
5,1,0,0,0,12.4
6,1,0,0,0,20.0
7,1,0,0,0,79.7
8,1,1,0,0,70.8
9,1,1,0,0,45.9
10,1,1,0,0,47.5
11,1,1,0,0,77.8
12,1,1,0,0,70.9
13,1,1,0,0,84.8
14,1,1,0,0,49.8
15,1,1,0,0,34.6
16,1,0,1,0,71.4
17,1,0,1,0,55.0
18,1,0,1,0,54.0
19,1,0,1,0,27.9
20,1,0,1,0,40.6
21,1,0,1,0,33.0
22,1,0,1,0,22.2
23,1,0,1,0,80.5
24,1,0,1,0,80.0
25,1,0,1,0,41.0
26,1,0,0,1,35.0
27,1,0,0,1,33.0
28,1,0,0,1,34.2
29,1,0,0,1,43.2
30,1,0,0,1,20.0
31,1,0,0,1,37.0
32,1,0,0,1,28.2
33,1,0,0,1,46.4
34,1,0,0,1,64.9
35,1,0,0,1,59.4

In [34]:
test = sm.OLS(y, X).fit()

In [35]:
print test.params

Intercept                  8.042430
C(Treatment)[T.Method2]    6.270815
C(Treatment)[T.Method3]   -2.449790
C(Treatment)[T.Method4]   -5.185752
Income                     0.322535
dtype: float64

In [ ]:
print test